version: '3.1'

services:

  db:
    image: mariadb
    volumes: 
      - './db:/docker-entrypoint-initdb.d'
    environment:
      MYSQL_ROOT_PASSWORD: r00tp4ssw0rd
      MARIADB_DATABASE: sakila

  app:
    build: ./app
    restart: on-failure
    volumes: 
      - ./app:/usr/src/app
    ports: 
      - 8080:8000
    depends_on: 
      - 'db'
    environment:
      MYSQL_HOST: "db"
      MYSQL_USER: "app"
      MYSQL_PASSWORD: "appPass"
      MYSQL_DB: "sakila"